provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: bunctions/helloworld:latest
    labels:
      com.openfaas.scale.zero: true
    environment:
      content_type: "application/json"
      combine_output: "false"
